# -*- coding: utf-8 -*-
"""PalmerPenguinsM1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lWElrJd3gNMI4pYdH0NLmkM1IpT4dAEj
"""

# PalmerPenguins.py
# Pamela Brauda
# 09/23/2026
# Introduces the Palmer Penguin Species

#Constants representing the names and total of species
SP_CHINSTRAP = "Chinstrap"
SP_GENTOO = "Gentoo"
SP_ADELIE = "Adelie"

TOTAL_SPECIES = 3

#Output the names with introduction text
print("Introducing the Palmer Penguins:")
print("\t" + SP_CHINSTRAP + "!")
print("\t" + SP_GENTOO + "!")
print("and last but not least...")
print("\t" + SP_ADELIE + "!")
print()
print("There are a total of " +
      str(TOTAL_SPECIES) +
      " penguin species in this dataset.")